[package]
name = "whisperkey_core"
version = "0.1.0"
edition = "2021"


[dependencies]
whisper-rs = { workspace = true }
cpal = { workspace = true }
enigo = { workspace = true }
clap = { workspace = true }
stakker = "0.2.12"
tracing = "0.1"
thiserror = "1.0"
