[package]
name = "whisperkey_core"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
whisper-rs = { workspace = true }
cpal = { workspace = true }
enigo = { workspace = true }
clap = { workspace = true }
